s_digit ::= [0-9]
s_lowercase ::= [a-z]
s_uppercase ::= [A-Z]
s_letter ::= s_lowercase | s_uppercase


expression ::= e_add

e_add ::= e_mul "+" e_mul
e_mul ::= e_literal "*" e_literal
e_literal ::= l_number | l_string

l_string ::= '"' [^"] '"'
l_number ::= '-'? digit*